### ISSUE TITLE
Error when compile and execute 

### ISSUE THREAD

**Issue by blackbirdsr71br** [javierpe/DynamicListCompose#11]
Good Morning.

Today I probe your repository but when I install  the app return an error, the error is follow:
çFATAL EXCEPTION: main
                                                                                                    Process: com.nucu.dynamiclistcompose, PID: 21616
                                                                                                    java.lang.IllegalStateException: The NavDeepLink must have an uri, action, and/or mimeType.
                                                                                                    	at androidx.navigation.NavDeepLinkDslBuilder.build$navigation_common_release(NavDeepLinkDslBuilder.kt:60)
                                                                                                    	at androidx.navigation.NavDeepLinkDslBuilderKt.navDeepLink(NavDeepLinkDslBuilder.kt:26)
                                                                                                    	at com.javi.places.page.impl.destinations.PlacesPageDestination.getDeepLinks(PlacesPageDestination.kt:33)

**Comment by javierpe** [comment]
Hello! Thank you very much for looking at the repository! This is a problem that is already reported with this [ticket](https://github.com/raamcosta/compose-destinations/issues/178). 

My recommendation is that you delete the build directory of the following modules and rebuild project:

- cards-page 
- home
- places-page
- product_detail

Let me know if that solves the problem. For now, this issue is out of reach and most likely it will migrate to another navigation system.
